Fixing the artifact issue in ci

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -94,6 +94,17 @@ jobs:
           # export to GITHUB_ENV for subsequent steps
           Add-Content -Path $env:GITHUB_ENV -Value "RUN_TIMESTAMP=$ts"
 
+
+
+      - name: Debug Suite File
+        shell: bash
+        run: |
+              echo "Suite path:"
+              echo "src/test/runners/${{ matrix.suite }}"
+              ls -l src/test/runners/
+              cat src/test/runners/${{ matrix.suite }} || echo "File missing"
+
+
       - name: Run Maven Tests
         working-directory: ${{ env.WORKDIR }}
         shell: bash
@@ -110,6 +121,7 @@ jobs:
                  -Dsurefire.suiteXmlFiles=src/test/runners/${{ matrix.suite }} \
                  -DrunTimestamp="${{ env.RUN_TIMESTAMP }}" \
                  -Dlogs.dir="$ABS_LOGS_DIR"
+
 
       - name: Copy ExtentReport and publish to gh-pages (fixed)
         if: ${{ always() && github.ref != 'refs/heads/gh-pages' }}
@@ -266,7 +278,7 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: extent-report-bundle
+          name: extent-report-${{ matrix.suite }}
           path: ${{ env.WORKDIR }}/artifacts/extent-artifact
           retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
           if-no-files-found: warn
